### ISSUE TITLE
Hoping for a little guidance

### ISSUE THREAD

**Issue by urthling** [mikesmullin/amf-js#6]
Hoping you might be able to help -- I'm using this successfully to decode but I'm running into an issue with Externalized serialization of "flex.messaging.io.ArrayCollection"

Soooooo hope you're active!

**Comment by mikesmullin** [comment]
We've only implemented the types we needed. There may be many more types, including third-party types, which I expect you as the user to implement, and share-back upstream via PR, if you need them.

**Comment by urthling** [comment]
Understood.  That's not a 3rd party type -- and I couldn't figure it out, so I went with replacing this class with a native java array server side before pushing to client which works for us.

Anyway -- thank you for this library -- working well otherwise!

**Comment by mikesmullin** [comment]
The Haxe OpenFL project also has an implementation of an AMF decoder which you might take a look at.
https://api.haxeflixel.com/openfl/utils/ByteArray.html#readObject

**Comment by urthling** [comment]
Ah, I'll take a look thank you Mike!
