### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by rezonant** [mikesmullin/amf-js#7]
Hello,

I'm building an AMF library and found this, am wondering if you could declare a license for it?

I don't really need any implementation code from this, as I'm trying to build direct from spec in order to make a comprehensive implementation, but I'd like to bring over tests from various implementations out there to help prove the approach-- the library I'm building is unrestricted MIT so all of this work will be reciprocally useful to other implementations. I'm conscious of the fact that I need to be mindful where these implementations have incompatible license terms, even if it is only the tests.

Find the implementation at https://github.com/astronautlabs/amf

**Comment by mikesmullin** [comment]
Cool. You're super nice.

I added MIT license.
